DROP TABLE IF EXISTS `forbidden`;

CREATE TABLE `forbidden`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `word` VARCHAR(50) NOT NULL,
    PRIMARY KEY(`id`),
    UNIQUE KEY(`word`)
) ENGINE=InnoDB;